spring:
  datasource:
    url: jdbc:mysql://localhost/burndown_local?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  locations: classpath:db/migration,classpath:db/fixtures
  clean-on-validation-error: true